/* eslint-disable @typescript-eslint/no-explicit-any */
import { IHero } from "@/modules/data/getHeroData";

const memoizedCampDataBuilder = new Map<string, Record<string, number>>();

export function CampDataBuilder(
  personalities: string[],
): Record<string, number> {
  const key = personalities.join(",");
  if (memoizedCampDataBuilder.has(key)) {
    return memoizedCampDataBuilder.get(key)!;
  }

  const res: Record<string, number> = {};
  const p = Array.isArray(personalities) ? personalities : [-1, -1];

  for (let i = 0; i < campData.topics.length; i++) {
    const topic = campData.topics[i];
    res[topic.name] =
      Math.max(topic.values[p[0] as number] || 0, 0) +
      Math.max(topic.values[p[1] as number] || 0, 0);
  }

  memoizedCampDataBuilder.set(key, res);
  return res;
}

export function getHeroCombinations(heroList: IHero[]): IHero[][] {
  const getCombinations = (arr: IHero[], selectNumber: number): IHero[][] => {
    const results: IHero[][] = [];
    if (selectNumber === 1) return arr.map((value) => [value]);

    arr.forEach((fixed, index, origin) => {
      const rest = origin.slice(index + 1);
      const combinations = getCombinations(rest, selectNumber - 1);
      const attached = combinations.map((combination) => [
        fixed,
        ...combination,
      ]);
      results.push(...attached);
    });

    return results;
  };

  const lockedHeroes = heroList.filter((hero) => hero.isLock);
  const unlockedHeroes = heroList.filter((hero) => !hero.isLock);

  if (lockedHeroes.length >= 4) {
    return [lockedHeroes.slice(0, 4)];
  } else {
    const requiredCount = 4 - lockedHeroes.length;
    const remainingCombinations = getCombinations(
      unlockedHeroes,
      requiredCount,
    );
    return remainingCombinations.map((combination) => [
      ...lockedHeroes,
      ...combination,
    ]);
  }
}

export function getBestChatOptions(team: IHero[]): {
  team: IHero[];
  bestChatOption1: any;
  bestChatOption2: any;
  score: number;
} {
  const arrOfScoreObj: Array<{
    option_en: string;
    option_kr: string;
    hero: IHero;
    score: number;
  }> = [];

  team.forEach((hero) => {
    arrOfScoreObj.push({
      option_en: hero.camping.topics_en[0],
      option_kr: hero.camping.topics_kr[0],
      hero: hero,
      score: 0,
    });
    arrOfScoreObj.push({
      option_en: hero.camping.topics_en[1],
      option_kr: hero.camping.topics_kr[1],
      hero: hero,
      score: 0,
    });
  });

  arrOfScoreObj.forEach((optionObj) => {
    let score = 0;
    team.forEach((hero: IHero) => {
      score +=
        hero.camping.common[
          optionObj.option_en as keyof typeof hero.camping.common
        ];
    });
    score -=
      optionObj.hero.camping.common[
        optionObj.option_en as keyof typeof optionObj.hero.camping.common
      ];
    optionObj.score = score;
  });

  arrOfScoreObj.sort((a, b) => b.score - a.score);

  const uniqueOptions = new Set();
  const uniqueArrOfScoreObj = arrOfScoreObj.filter((obj) => {
    if (uniqueOptions.has(obj.option_en)) {
      return false;
    } else {
      uniqueOptions.add(obj.option_en);
      return true;
    }
  });

  const optimalCampForTeam = {
    team: team,
    bestChatOption1: uniqueArrOfScoreObj[0],
    bestChatOption2: uniqueArrOfScoreObj[1],
    score: uniqueArrOfScoreObj[0].score + uniqueArrOfScoreObj[1].score,
  };

  return optimalCampForTeam;
}

export const campData = {
  personalities: [
    "Introvert",
    "Hot and Cold",
    "Cherub",
    "Narcissist",
    "Arrogant",
    "Debate Addict",
    "Academic",
    "Heroism",
    "Traumatized",
    "Loyal",
    "Realistic",
    "Selfish",
    "Individualistic",
    "Altruistic",
    "Glutton",
    "Alcoholic",
    "Lovesick",
    "Lustful",
    "Psychopath",
    "Religious",
    "Optimistic",
    "Pessimistic",
    "Indifferent",
    "Natural",
    "Obsessive",
    "Hard Worker",
    "Extrovert",
    "Envious",
    "Cool-Headed",
    "Free",
    "Escapist",
  ],
  topics: [
    {
      name: "Criticism",
      values: [
        -1,
        -2,
        -2,
        3,
        5,
        5,
        2,
        -5,
        3,
        -1,
        3,
        3,
        2,
        -3,
        null,
        2,
        null,
        null,
        3,
        -3,
        -2,
        3,
        0,
        -2,
        0,
        2,
        0,
        3,
        2,
        1,
        2,
      ],
    },
    {
      name: "Reality Check",
      values: [
        -3,
        0,
        -2,
        3,
        -3,
        3,
        2,
        -3,
        -3,
        1,
        3,
        0,
        2,
        -3,
        null,
        -2,
        null,
        null,
        2,
        0,
        -2,
        3,
        0,
        -2,
        -3,
        1,
        0,
        0,
        2,
        -1,
        -3,
      ],
    },
    {
      name: "Heroic Tale",
      values: [
        1,
        0,
        2,
        3,
        5,
        -3,
        0,
        3,
        1,
        3,
        -1,
        0,
        0,
        -3,
        null,
        3,
        null,
        null,
        -3,
        0,
        3,
        -2,
        1,
        2,
        0,
        2,
        3,
        2,
        0,
        0,
        -1,
      ],
    },
    {
      name: "Comforting Cheer",
      values: [
        3,
        3,
        2,
        5,
        3,
        0,
        1,
        3,
        -3,
        3,
        0,
        0,
        2,
        3,
        null,
        3,
        null,
        null,
        3,
        3,
        0,
        5,
        0,
        2,
        -1,
        5,
        3,
        -2,
        -2,
        1,
        3,
      ],
    },
    {
      name: "Cute Cheer",
      values: [
        3,
        3,
        2,
        5,
        4,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        3,
        null,
        2,
        null,
        null,
        0,
        0,
        3,
        -3,
        1,
        2,
        1,
        2,
        3,
        2,
        0,
        2,
        2,
      ],
    },
    {
      name: "Heroic Cheer",
      values: [
        3,
        0,
        2,
        3,
        -3,
        1,
        1,
        3,
        0,
        5,
        2,
        0,
        2,
        2,
        null,
        3,
        null,
        null,
        -3,
        2,
        3,
        -1,
        0,
        2,
        1,
        2,
        3,
        3,
        0,
        1,
        -3,
      ],
    },
    {
      name: "Sad Memory",
      values: [
        0,
        3,
        2,
        0,
        0,
        -3,
        0,
        3,
        3,
        3,
        0,
        0,
        1,
        5,
        null,
        1,
        null,
        null,
        4,
        4,
        1,
        -2,
        0,
        2,
        -3,
        3,
        -2,
        -1,
        0,
        1,
        3,
      ],
    },
    {
      name: "Joyful Memory",
      values: [
        2,
        2,
        2,
        0,
        0,
        0,
        0,
        3,
        3,
        2,
        0,
        2,
        3,
        3,
        null,
        2,
        null,
        null,
        0,
        2,
        4,
        1,
        1,
        2,
        0,
        3,
        3,
        1,
        1,
        1,
        3,
      ],
    },
    {
      name: "Happy Memories",
      values: [
        2,
        2,
        2,
        0,
        2,
        0,
        0,
        3,
        0,
        2,
        0,
        0,
        2,
        3,
        null,
        1,
        null,
        null,
        -2,
        2,
        2,
        1,
        0,
        2,
        -1,
        -3,
        2,
        1,
        0,
        1,
        2,
      ],
    },
    {
      name: "Unique Comment",
      values: [
        0,
        1,
        0,
        2,
        0,
        -1,
        -3,
        2,
        3,
        0,
        0,
        0,
        0,
        0,
        null,
        1,
        null,
        null,
        5,
        2,
        3,
        -1,
        1,
        0,
        3,
        0,
        0,
        1,
        3,
        2,
        1,
      ],
    },
    {
      name: "Self-Indulgent",
      values: [
        -3,
        -3,
        2,
        0,
        -3,
        1,
        5,
        -1,
        1,
        -2,
        -1,
        -2,
        0,
        -2,
        null,
        2,
        null,
        null,
        1,
        0,
        1,
        -2,
        0,
        2,
        -1,
        -3,
        2,
        2,
        0,
        1,
        -2,
      ],
    },
    {
      name: "Occult",
      values: [
        0,
        0,
        -1,
        -3,
        3,
        -3,
        3,
        0,
        3,
        -2,
        -1,
        0,
        0,
        -1,
        null,
        -2,
        null,
        null,
        3,
        -3,
        1,
        4,
        0,
        -1,
        1,
        0,
        1,
        2,
        0,
        1,
        2,
      ],
    },
    {
      name: "Myth",
      values: [
        1,
        0,
        2,
        2,
        5,
        3,
        5,
        3,
        0,
        1,
        -1,
        0,
        0,
        1,
        null,
        0,
        null,
        null,
        -3,
        3,
        1,
        -3,
        0,
        2,
        0,
        0,
        1,
        4,
        0,
        1,
        -3,
      ],
    },
    {
      name: "Bizarre Story",
      values: [
        2,
        0,
        -1,
        -3,
        -3,
        -3,
        0,
        -2,
        -2,
        -1,
        -2,
        0,
        -2,
        -1,
        null,
        -2,
        null,
        null,
        5,
        -2,
        1,
        3,
        0,
        -1,
        5,
        0,
        2,
        0,
        0,
        2,
        -2,
      ],
    },
    {
      name: "Food Story",
      values: [
        0,
        0,
        4,
        0,
        3,
        0,
        0,
        2,
        0,
        2,
        0,
        0,
        1,
        0,
        null,
        3,
        null,
        null,
        -3,
        1,
        3,
        -2,
        4,
        4,
        0,
        3,
        1,
        2,
        0,
        1,
        2,
      ],
    },
    {
      name: "Horror Story",
      values: [
        -1,
        -2,
        -5,
        -3,
        -2,
        0,
        -5,
        2,
        0,
        0,
        2,
        3,
        0,
        -2,
        null,
        -3,
        null,
        null,
        5,
        0,
        1,
        -2,
        -2,
        -5,
        3,
        -1,
        3,
        0,
        0,
        1,
        -2,
      ],
    },
    {
      name: "Gossip",
      values: [
        3,
        1,
        1,
        1,
        -1,
        3,
        2,
        -2,
        -3,
        -3,
        1,
        3,
        -2,
        1,
        null,
        0,
        null,
        null,
        -3,
        -1,
        1,
        -3,
        0,
        1,
        0,
        -3,
        2,
        0,
        0,
        1,
        1,
      ],
    },
    {
      name: "Dream",
      values: [
        1,
        2,
        2,
        2,
        0,
        2,
        0,
        2,
        2,
        1,
        -3,
        0,
        2,
        3,
        null,
        2,
        null,
        null,
        2,
        2,
        2,
        0,
        0,
        2,
        2,
        3,
        2,
        3,
        0,
        4,
        0,
      ],
    },
    {
      name: "Complain",
      values: [
        -3,
        -1,
        1,
        -2,
        -2,
        2,
        1,
        -3,
        -3,
        -1,
        0,
        3,
        2,
        1,
        null,
        2,
        null,
        null,
        -5,
        2,
        1,
        -2,
        0,
        1,
        -5,
        -5,
        0,
        -2,
        0,
        1,
        2,
      ],
    },
    {
      name: "Belief",
      values: [
        3, 0, 0, 4, -3, -1, 0, -1, 5, -3, 2, 3, 1, -3, 0, 3, 0, 0, 3, 3, 2, -3,
        0, 1, 3, 1, 1, 3, 0, -1, -3,
      ],
    },
    {
      name: "Interesting Story",
      values: [
        2,
        1,
        1,
        1,
        -1,
        1,
        2,
        1,
        1,
        0,
        -1,
        0,
        1,
        1,
        null,
        3,
        null,
        null,
        1,
        0,
        2,
        1,
        1,
        1,
        0,
        1,
        2,
        1,
        1,
        5,
        3,
      ],
    },
  ],
};
